name: check

on:
  # Check https://mubi.com/live for the currently playing film every two minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Get a blob representing the currently streaming film at https://mubi.com/live
        uses: githubocto/flat@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          http_url: https://mubi.com/live.json
          downloaded_filename: live.json
          postprocess: postprocess.ts
