name: check

on:
  # Check https://mubi.com/live for the currently playing film every two minutes
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Extract current film data
        id: extract_before
        run: echo ::set-output name=title::$(jq .title film.json)

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Get a blob representing the currently streaming film at https://mubi.com/live
        uses: githubocto/flat@v3
        with:
          http_url: https://mubi.com/live.json
          downloaded_filename: live.json
          postprocess: postprocess.ts

      - name: Extract updated film data
        id: extract_after
        run: echo ::set-output name=title::$(jq .title film.json)

      - name: Repository dispatch
        if: ${{ steps.extract_before.outputs.title != steps.extract_after.outputs.title }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: jdennes/mubi-live
          event-type: new-film-streaming
          client-payload: '{}'
