name: notify

on:
  push:
    branches: [ main ]
    paths:
      - film.json # Only notify when film.json changes

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Extract film data
        id: extract
        run: echo ::set-output name=title::$(jq .title film.json)

      - name: Test output
        run: echo ${{ steps.extract.outputs.title }}
