name: notify

on:
  push:
    branches: [ main ]
    paths:
      - film.json # Only notify when film.json changes

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Extract film data
        id: extract
        run: |
          echo ::set-output name=title::$(jq .title film.json)
          echo ::set-output name=year::$(jq .year film.json)
          echo ::set-output name=country::$(jq .country film.json)
          echo ::set-output name=directors::$(jq .directors film.json)
          echo ::set-output name=web_url::$(jq .web_url film.json)
          echo ::set-output name=excerpt::$(jq .excerpt film.json)

      - name: Notify via a new issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/new-film.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ steps.extract.outputs.title }}
          YEAR: ${{ steps.extract.outputs.year }}
          COUNTRY: ${{ steps.extract.outputs.country }}
          DIRECTORS: ${{ steps.extract.outputs.directors }}
          WEB_URL: ${{ steps.extract.outputs.web_url }}
          EXCERPT: ${{ steps.extract.outputs.excerpt }}
